appx/urls.py
from django.urls import path
from appx.views import lsd_details, lsd_create, lsd_delete, all_details,cart_v, add_v,del_v

app_name = "lsd"
urlpatterns = [
    path ('details/<int:m_id>/',lsd_details, name="details"),
    path ('details/<int:m_id>/delete/',lsd_delete, name="delete" ),
    path ('details/',all_details,name="all_details"),
    path ('create/',lsd_create,name ="create"),
    path ('cart/',cart_v,name ="cart"),
    path ('details/<int:m_id>/add/',add_v,name = "cart_add"),
    path ('details/<int:m_id>/del/',del_v,name ="del"),
]

blog/urls.py
from django.urls import path
from .views import clist_view, cmform_v ,cdetails_view, cdelete_v,cupdate_v,regis, login_v ,logout_v 

app_name = "blog" 
urlpatterns =[
	path ("",clist_view.as_view(), name = "list"),
	path ("<int:pk>/",cdetails_view.as_view(), name = "details"),
	path ("<int:pk>/ud",cupdate_v.as_view(), name = "update"),
	path ("<int:pk>/delete/", cdelete_v.as_view(),name ="delete"),
	path ("add/",cmform_v.as_view(), name ="add"),
	path ("regis/",regis.as_view(),name="regis"),
	path ("login/",login_v,name= "login"),
	path ("logout/",logout_v,name= "logout"),
]

projectx/urls.py
from django.conf import settings 
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include
from pages.views import home_view,about_view,search_v
from pages.views import h_view 

urlpatterns = [ 
    path ('blog/',include('blog.urls')),
    path('lsd/', include('appx.urls')),
	path('',home_view,name ="home"),
    path('home/',home_view, name ="home"),
    path('s/',search_v, name ="search"),
	path('about/',about_view,name ="about"),
    path('admin/', admin.site.urls),
    path ('h/',h_view), 
]
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root= settings.STATIC_ROOT) 
    urlpatterns+= static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

templates/about.html
{% extends "base.html" %} 
{% block con %}

<div class="container"> 
<h2>
About
</h2> 
</div>
<hr>
{% endblock %}

templates/base.html
<!--doctype html--> 
<html>
<head>
<title>The xox </title>

 <!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>  
	<div class="container">
	<div class="row" style="background-color: #f1f1f1">
	<div class="col-7">
	{% include "navb.html" %} 
	</div> 
	<div class="col ml-auto">
	{%include "user.html"%}
	</div>
	</div>
	<div class="col-10">
	{% block con %}
	{% endblock %}
	</div>
	</div>  
</body>
</html>

templates/home.html
{% extends "base.html" %} 
{% block con %}
<div class="container"> 
<h2>
Home 
</h2>
<hr>
<h3>
{{ text }}  <br>
<br>
here is some list:
</h3>
<p>
	<ol>
		{%for item in m_list%}
		{%if item == 332%}
		<li>{{item | add:22}}*</li>
		{%elif item == 22%}
		<li>{{item}}=22</li>
		{%else%}
		<li> {{item}}</li>
		{%endif%}
		{%endfor%}
	</ol>
</p>
</div>
{% endblock %}

templates/navb.html
<nav class="nav-bar pt-2 pl-5">
	<h4>
	 <a href="{%url 'home'%}">Home</a>&nbsp&nbsp
	 <a href="{%url 'about'%}">About</a>&nbsp&nbsp 
	 <a href="{%url 'lsd:all_details'%}">All Lsd</a>&nbsp&nbsp 
	 <a href="{%url 'lsd:create'%}">Add Lsd</a>&nbsp&nbsp 
	 <a href="{%url 'blog:list'%}">Blog</a>&nbsp&nbsp 
	 <a href="{%url 'lsd:cart'%}">Cart</a>&nbsp&nbsp
	 </h4> 
</nav>  

templates/search.html
{% extends "base.html" %} 
{% block con %}
<h1>
Home 
</h1> 
<p>
	<ul>
		<h3><li>You searched for: </li></h3>
		<hr>
		<li>{{x}}</li>
	</ul>
</p>
{% endblock %}

templates/user.html
<div class="row"> 
<div class = "col-7 ml-auto pt-3" >	 
	<form action="{%url 'search'%}" method="GET">
		<input type="text" name="search"/> 
		<button type="submit" class="btn-primary">&nbspSearch&nbsp</button>
	</form>  
</div>
<div class="col-3 mr-auto pt-2">
	{%if request.user.is_authenticated%} 
	<div class="row ">
	<h4>&nbsp&nbsp{{request.user}} ^ </h4> &nbsp<a href="{% url 'blog:logout'%}">logout</a>
	</div>
	{%else%}
	<div class="row ml-auto mt-3">
    <a href="{% url 'blog:login'%}"> LogIn</a> &nbsp&nbsp&nbsp&nbsp
    <a href="{% url 'blog:regis'%}"> SignUp</a> 
	</div>
	{%endif%}
</div> 
</div>